// frontend react/src/components/cart/CartPage/CartPage.tsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { CartLine, cartStateService } from '../../../services/cartStateService';
import { cardService } from '../../../services/cardService';
import Swal from 'sweetalert2';
import './CartPage.css';

export const CartPage: React.FC = () => {
  const [items, setItems] = useState<CartLine[]>(cartStateService.getItems());
  const [isProcessing, setIsProcessing] = useState(false);

  useEffect(() => {
    setItems(cartStateService.getItems());
    const unsubscribe = cartStateService.subscribe(() => {
      setItems(cartStateService.getItems());
    });
    return unsubscribe;
  }, []);

  const updateQuantity = (cardId: string, quantity: number) => {
    if (!Number.isFinite(quantity) || quantity < 1) return;
    cartStateService.updateQuantity(cardId, quantity);
  };

  const remove = (cardId: string) => {
    cartStateService.removeCard(cardId);
  };

  const clear = async () => {
    const result = await Swal.fire({
      title: '¿Estás seguro?',
      text: 'Se eliminarán todas las cartas del carrito',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Sí, vaciar carrito',
      cancelButtonText: 'Cancelar'
    });

    if (result.isConfirmed) {
      cartStateService.clear();
      await Swal.fire({
        icon: 'success',
        title: '¡Carrito vaciado!',
        text: 'Se han eliminado todas las cartas del carrito',
        timer: 2000,
        showConfirmButton: false
      });
    }
  };

  const checkout = async () => {
    if (isProcessing) return;

    setIsProcessing(true);
    
    if (items.length === 0) {
      await Swal.fire({
        icon: 'warning',
        title: 'Carrito vacío',
        text: 'No hay cartas en el carrito para procesar',
        confirmButtonText: 'Entendido'
      });
      setIsProcessing(false);
      return;
    }

    try {
      const updates = items.map(item => {
        const nextStock = Math.max(item.card.stock - item.quantity, 0);
        return cardService.updateCard({
          ...item.card,
          stock: nextStock
        });
      });

      await Promise.all(updates);

      await Swal.fire({
        icon: 'success',
        title: '¡Compra completada!',
        text: 'Tu pedido ha sido procesado exitosamente',
        confirmButtonText: 'Continuar'
      });
      cartStateService.clear();
    } catch (error) {
      console.error('Error al actualizar stock:', error);
      await Swal.fire({
        icon: 'error',
        title: 'Error',
        text: 'No se pudo actualizar el stock. Inténtalo de nuevo.',
        confirmButtonText: 'Entendido'
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const total = items.reduce((sum, item) => sum + item.card.price * item.quantity, 0);

  return (
    <div className="container-fluid py-4 cart-container">
      <div className="row">
        <div className="col-12">
          <h2 className="display-5 mb-4 fw-bold">Mi Carrito</h2>
        </div>
      </div>

      {items.length === 0 ? (
        <div className="empty-state text-center py-5">
          <div className="mb-3" style={{ fontSize: '3rem' }}>🛒</div>
          <h3>Tu carrito está vacío</h3>
          <p className="text-light">Añade cartas a tu carrito para comprar</p>
          <Link to="/card/list" className="btn btn-primary">
            Ver catálogo
          </Link>
        </div>
      ) : (
        <div className="row g-4">
          <div className="col-lg-8">
            <div className="cart-items-section">
              {items.map(item => (
                <div key={item.card._id} className="cart-item">
                  <img src={item.card.imageUrl} alt={item.card.name} className="cart-item-image" />
                  <div className="cart-item-details">
                    <h5>{item.card.name}</h5>
                    <p className="text-light">{item.card.collection} • {item.card.condition}</p>
                    <p className="fw-bold">{item.card.price.toFixed(2)}€</p>
                  </div>
                  <div className="cart-item-quantity">
                    <label>Cantidad:</label>
                    <input
                      type="number"
                      min="1"
                      value={item.quantity}
                      onChange={(e) => updateQuantity(item.card._id, Number(e.target.value))}
                      className="form-control"
                    />
                  </div>
                  <div className="cart-item-total">
                    <p className="fw-bold">{(item.card.price * item.quantity).toFixed(2)}€</p>
                  </div>
                  <button
                    className="remove-btn"
                    onClick={() => remove(item.card._id)}
                  >
                    ✕ Eliminar
                  </button>
                </div>
              ))}
            </div>
          </div>

          <div className="col-lg-4">
            <div className="cart-summary">
              <h4 className="mb-3">Resumen del pedido</h4>
              <div className="summary-row">
                <span>Subtotal:</span>
                <span>{total.toFixed(2)}€</span>
              </div>
              <div className="summary-row">
                <span>Artículos:</span>
                <span>{items.length}</span>
              </div>
              <div className="summary-divider"></div>
              <div className="summary-row total-row">
                <span>Total:</span>
                <span>{total.toFixed(2)}€</span>
              </div>
              <button
                className="btn btn-success btn-lg w-100 mt-3"
                onClick={checkout}
                disabled={isProcessing}
              >
                {isProcessing ? 'Procesando...' : 'Proceder al pago'}
              </button>
              <Link to="/card/list" className="btn btn-outline-secondary btn-lg w-100 mt-2">
                Seguir comprando
              </Link>
              <button
                className="btn btn-outline-danger btn-lg w-100 mt-2"
                onClick={clear}
              >
                Vaciar carrito
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

// frontend angular/src/app/components/cart/cart-page/cart-page.component.ts
import { Component, inject } from '@angular/core';
import { AsyncPipe, CurrencyPipe } from '@angular/common';
import { CartStateService } from '../../../service/cart-state.service';
import { RouterLink } from '@angular/router';
import { map } from 'rxjs';

@Component({
  selector: 'app-cart-page',
  imports: [AsyncPipe, CurrencyPipe, RouterLink],
  templateUrl: './cart-page.component.html',
  styleUrl: './cart-page.component.css'
})
export class CartPageComponent {
  private readonly cartState = inject(CartStateService);

  readonly items$ = this.cartState.items$;
  readonly total$ = this.cartState.items$.pipe(
    map((items) => items.reduce((sum, item) => sum + item.card.price * item.quantity, 0))
  );

  updateQuantity(cardId: string, value: string): void {
    const quantity = Number.parseInt(value, 10);
    if (!Number.isFinite(quantity)) {
      return;
    }
    this.cartState.updateQuantity(cardId, quantity);
  }

  remove(cardId: string): void {
    this.cartState.removeCard(cardId);
  }

  clear(): void {
    this.cartState.clear();
  }
}

<div class="container-fluid my-4">
  <div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3">
    <h2 class="display-6 mb-0">Carrito</h2>
    <button class="btn btn-outline-danger" type="button" (click)="clear()">Vaciar carrito</button>
  </div>

  @if ((items$ | async)?.length === 0) {
    <div class="alert alert-info">Aun no hay cartas en el carrito.</div>
    <button class="btn btn-primary" routerLink="/card/list">Volver al listado</button>
  } @else {
    <div class="table-responsive">
      <table class="table align-middle">
        <thead class="table-light">
          <tr>
            <th>Imagen</th>
            <th>Nombre</th>
            <th class="text-end">Precio</th>
            <th class="text-center">Cantidad</th>
            <th class="text-end">Subtotal</th>
            <th class="text-center">Acciones</th>
          </tr>
        </thead>
        <tbody>
          @for (item of items$ | async; track item.card._id) {
            <tr>
              <td>
                <img class="cart-thumb" [src]="item.card.imageUrl" [alt]="item.card.name">
              </td>
              <td>{{ item.card.name }}</td>
              <td class="text-end">{{ item.card.price | currency:'EUR' }}</td>
              <td class="text-center">
                <input class="form-control form-control-sm text-center" type="number" min="1"
                       [value]="item.quantity" (change)="updateQuantity(item.card._id, $any($event.target).value)">
              </td>
              <td class="text-end">{{ (item.card.price * item.quantity) | currency:'EUR' }}</td>
              <td class="text-center">
                <button class="btn btn-sm btn-outline-danger" type="button" (click)="remove(item.card._id)">Quitar</button>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>

    <div class="d-flex justify-content-end mt-3">
      <div class="total-box">
        <div class="label">Total</div>
        <div class="value">{{ total$ | async | currency:'EUR' }}</div>
      </div>
    </div>
  }
</div>
