// frontend angular/src/app/components/card/card-detail/card-detail.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { ServiceCardService } from '../../../service/service-card.service';
import { Card } from '../../../common/interface-card';
import { CartStateService } from '../../../service/cart-state.service';

@Component({
  selector: 'app-card-detail',
  imports: [RouterLink],
  templateUrl: './card-detail.component.html',
  styleUrl: './card-detail.component.css'
})
export class CardDetailComponent implements OnInit {
  private readonly cardService = inject(ServiceCardService);
  private readonly cartState = inject(CartStateService);
  private readonly route = inject(ActivatedRoute);

  card: Card | null = null;
  loading = true;
  errorMessage = '';
  statusMessage = '';

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (!id) {
      this.loading = false;
      this.errorMessage = 'No se encontro la carta solicitada.';
      return;
    }

    this.cardService.getCard(id).subscribe({
      next: (data) => {
        this.card = data.status;
      },
      error: () => {
        this.errorMessage = 'No se pudo cargar la carta.';
      },
      complete: () => {
        this.loading = false;
      }
    });
  }

  addToCart(): void {
    if (!this.card) {
      return;
    }

    this.cartState.addCard(this.card, 1);
    this.statusMessage = 'Carta agregada al carrito.';
  }
}

<div class="container-fluid my-4">
  @if (loading) {
    <div class="text-center">
      <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Cargando...</span>
      </div>
    </div>
  } @else if (errorMessage) {
    <div class="alert alert-danger" role="alert">{{ errorMessage }}</div>
  } @else if (card) {
    <div class="row g-4 align-items-start">
      <div class="col-md-5 col-lg-4">
        <img class="detail-image" [src]="card.imageUrl" [alt]="card.name">
      </div>
      <div class="col-md-7 col-lg-8">
        <div class="d-flex justify-content-between align-items-start flex-wrap gap-2">
          <h2 class="display-6 mb-0">{{ card.name }}</h2>
          <span class="badge text-bg-primary">{{ card.rarity }}</span>
        </div>
        <p class="text-muted mb-3">{{ card.collection }} · {{ card.type }}</p>

        <div class="info-grid">
          <div>
            <div class="label">Precio</div>
            <div class="value">{{ card.price }}</div>
          </div>
          <div>
            <div class="label">Stock</div>
            <div class="value">{{ card.stock }}</div>
          </div>
          <div>
            <div class="label">Idioma</div>
            <div class="value">{{ card.language }}</div>
          </div>
          <div>
            <div class="label">Estado</div>
            <div class="value">{{ card.condition }}</div>
          </div>
        </div>

        <div class="d-flex flex-wrap gap-2 mt-4">
          <button class="btn btn-primary" type="button" (click)="addToCart()">Agregar al carrito</button>
          <button class="btn btn-outline-secondary" routerLink="/card/list">Volver al listado</button>
          <button class="btn btn-outline-dark" routerLink="/card/edit/{{ card._id }}">Editar</button>
        </div>

        @if (statusMessage) {
          <div class="alert alert-success mt-3" role="alert">{{ statusMessage }}</div>
        }
      </div>
    </div>
  }
</div>

// frontend react/src/components/card/CardDetail/CardDetail.tsx
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { Card } from '../../../common/interfaces';
import { cardService } from '../../../services/cardService';
import { cartStateService } from '../../../services/cartStateService';
import { favoritesService } from '../../../services/favoritesService';
import Swal from 'sweetalert2';
import './CardDetail.css';

export const CardDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  
  const [card, setCard] = useState<Card | null>(null);
  const [loading, setLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState('');
  const [allCards, setAllCards] = useState<Card[]>([]);
  const [currentIndex, setCurrentIndex] = useState(-1);
  const [isFav, setIsFav] = useState(false);

  useEffect(() => {
    loadCards();
    const unsubscribe = favoritesService.subscribe(() => {
      if (card) {
        setIsFav(favoritesService.isFavorite(card._id));
      }
    });
    return unsubscribe;
  }, []);

  useEffect(() => {
    if (card) {
      setIsFav(favoritesService.isFavorite(card._id));
    }
  }, [card]);

  const loadCards = async () => {
    try {
      const data = await cardService.getCards();
      setAllCards(data.status);
      loadCurrentCard(data.status);
    } catch {
      loadCurrentCard([]);
    }
  };

  const loadCurrentCard = async (cards: Card[]) => {
    if (!id) {
      setLoading(false);
      setErrorMessage('No se encontro la carta solicitada.');
      return;
    }

    try {
      const data = await cardService.getCard(id);
      setCard(data.status);
      const index = cards.findIndex(c => c._id === data.status._id);
      setCurrentIndex(index);
    } catch {
      setErrorMessage('No se pudo cargar la carta.');
    } finally {
      setLoading(false);
    }
  };

  const addToCart = () => {
    if (!card) return;
    
    cartStateService.addCard(card, 1);
    Swal.fire({
      icon: 'success',
      title: '¡Añadido al carrito!',
      text: `${card.name} ha sido añadida al carrito`,
      timer: 2000,
      showConfirmButton: false,
      toast: true,
      position: 'top-end'
    });
  };

  const toggleFavorite = () => {
    if (!card) return;
    favoritesService.toggleFavorite(card);
  };

  const goToPrevious = () => {
    if (currentIndex > 0) {
      const prevCard = allCards[currentIndex - 1];
      navigate(`/card/detail/${prevCard._id}`);
      setLoading(true);
      loadCards();
    }
  };

  const goToNext = () => {
    if (currentIndex >= 0 && currentIndex < allCards.length - 1) {
      const nextCard = allCards[currentIndex + 1];
      navigate(`/card/detail/${nextCard._id}`);
      setLoading(true);
      loadCards();
    }
  };

  const hasPrevious = () => currentIndex > 0;
  const hasNext = () => currentIndex >= 0 && currentIndex < allCards.length - 1;

  if (loading) {
    return (
      <div className="container-fluid my-4 detail-container">
        <div className="text-center">
          <div className="spinner-border text-primary" role="status">
            <span className="visually-hidden">Cargando...</span>
          </div>
        </div>
      </div>
    );
  }

  if (errorMessage) {
    return (
      <div className="container-fluid my-4">
        <div className="alert alert-danger" role="alert">{errorMessage}</div>
      </div>
    );
  }

  if (!card) {
    return null;
  }

  return (
    <div className="container-fluid my-4 detail-container">
      <div className="d-flex justify-content-between mb-3">
        <button className="btn btn-outline-secondary" onClick={goToPrevious} disabled={!hasPrevious()}>
          ← Anterior
        </button>
        <button className="btn btn-outline-secondary" onClick={goToNext} disabled={!hasNext()}>
          Siguiente →
        </button>
      </div>

      <div className="row g-4 align-items-start">
        <div className="col-md-5 col-lg-4">
          <img className="detail-image" src={card.imageUrl} alt={card.name} />
        </div>
        <div className="col-md-7 col-lg-8">
          <div className="d-flex justify-content-between align-items-start flex-wrap gap-2">
            <h2 className="display-6 mb-0 fw-bold">{card.name}</h2>
            <span className="badge rarity-badge">{card.rarity}</span>
          </div>
          <p className="text-light mb-3">{card.collection} · {card.type}</p>

          <div className="info-grid">
            <div>
              <div className="label">Precio</div>
              <div className="value">{card.price.toFixed(2)}€</div>
            </div>
            <div>
              <div className="label">Stock</div>
              <div className="value">{card.stock}</div>
            </div>
            <div>
              <div className="label">Idioma</div>
              <div className="value">{card.language}</div>
            </div>
            <div>
              <div className="label">Estado</div>
              <div className="value">{card.condition}</div>
            </div>
          </div>

          <div className="d-flex flex-wrap gap-2 mt-4">
            <button className="btn btn-primary" onClick={addToCart}>
              🛒 Agregar al carrito
            </button>
            <button 
              className={`btn ${isFav ? 'btn-danger' : 'btn-outline-secondary'}`}
              onClick={toggleFavorite}
            >
              {isFav ? '❤️ Quitar de favoritos' : '🤍 Añadir a favoritos'}
            </button>
            <Link to="/card/list" className="btn btn-outline-secondary">Volver al listado</Link>
            <Link to={`/card/edit/${card._id}`} className="btn btn-outline-dark">Editar</Link>
          </div>
        </div>
      </div>
    </div>
  );
};
