// frontend angular/src/app/components/card/card-list/card-list.component.ts
import {Component, inject} from '@angular/core';
import {ServiceCardService} from '../../../service/service-card.service';
import {Card} from '../../../common/interface-card';
import {RouterLink} from '@angular/router';
import {CurrencyPipe} from '@angular/common';
import {FavoritesService} from '../../../service/favorites.service';
import {FormsModule} from '@angular/forms';

@Component({
  selector: 'app-card-list',
  imports: [
    RouterLink,
    CurrencyPipe,
    FormsModule
  ],
  templateUrl: './card-list.component.html',
  styleUrl: './card-list.component.css'
})
export class CardListComponent {
  private readonly cardService: ServiceCardService = inject(ServiceCardService);
  private readonly favoritesService = inject(FavoritesService);
  
  // Exponer Math para el template
  Math = Math;
  
  allCards: Card[] = [];
  cards: Card[] = [];
  paginatedCards: Card[] = [];
  collections: string[] = [];
  conditions: string[] = [];
  
  // Filtros
  selectedCollection = '';
  selectedCondition = '';
  minPrice: number | null = null;
  maxPrice: number | null = null;
  
  // Ordenamiento
  priceSort: 'none' | 'asc' | 'desc' = 'none';
  
  // Paginación
  currentPage = 1;
  itemsPerPage = 12;
  totalPages = 1;
  
  constructor() {
    this.loadCards();
  }

  private loadCards() {
    this.cardService.getCards().subscribe(
      {
        next: data =>{
          this.allCards = data.status;
          this.cards = [...this.allCards];
          this.extractFilters();
          this.updatePagination();
        },
        error: err =>{
          console.error('Error carga de cards:', err);
        },
        complete:() =>{
          console.log('Card List cargada correctamente');
        }
      }
    )
  }

  private extractFilters() {
    // Extraer colecciones únicas
    this.collections = [...new Set(this.allCards.map(card => card.collection))].sort();
    // Extraer condiciones únicas
    this.conditions = [...new Set(this.allCards.map(card => card.condition))].sort();
  }

  private updatePagination() {
    this.totalPages = Math.ceil(this.cards.length / this.itemsPerPage);
    if (this.currentPage > this.totalPages) {
      this.currentPage = Math.max(1, this.totalPages);
    }
    const startIndex = (this.currentPage - 1) * this.itemsPerPage;
    const endIndex = startIndex + this.itemsPerPage;
    this.paginatedCards = this.cards.slice(startIndex, endIndex);
  }

  applyFilters() {
    let filtered = [...this.allCards];
    
    // Filtrar por colección
    if (this.selectedCollection) {
      filtered = filtered.filter(card => card.collection === this.selectedCollection);
    }
    
    // Filtrar por condición
    if (this.selectedCondition) {
      filtered = filtered.filter(card => card.condition === this.selectedCondition);
    }
    
    // Filtrar por precio mínimo
    if (this.minPrice !== null && this.minPrice > 0) {
      filtered = filtered.filter(card => card.price >= this.minPrice!);
    }
    
    // Filtrar por precio máximo
    if (this.maxPrice !== null && this.maxPrice > 0) {
      filtered = filtered.filter(card => card.price <= this.maxPrice!);
    }
    
    // Aplicar ordenamiento
    if (this.priceSort === 'asc') {
      filtered.sort((a, b) => a.price - b.price);
    } else if (this.priceSort === 'desc') {
      filtered.sort((a, b) => b.price - a.price);
    }
    
    this.cards = filtered;
    this.currentPage = 1;
    this.updatePagination();
  }

  clearFilters() {
    this.selectedCollection = '';
    this.selectedCondition = '';
    this.minPrice = null;
    this.maxPrice = null;
    this.priceSort = 'none';
    this.cards = [...this.allCards];
    this.currentPage = 1;
    this.updatePagination();
  }

  togglePriceSort() {
    if (this.priceSort === 'none') {
      this.priceSort = 'asc';
    } else if (this.priceSort === 'asc') {
      this.priceSort = 'desc';
    } else {
      this.priceSort = 'none';
    }
    this.applyFilters();
  }

  // Métodos de paginación
  goToPage(page: number) {
    if (page >= 1 && page <= this.totalPages) {
      this.currentPage = page;
      this.updatePagination();
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  }

  nextPage() {
    this.goToPage(this.currentPage + 1);
  }

  previousPage() {
    this.goToPage(this.currentPage - 1);
  }

  getPageNumbers(): number[] {
    const pages: number[] = [];
    const maxVisiblePages = 5;
    
    if (this.totalPages <= maxVisiblePages) {
      for (let i = 1; i <= this.totalPages; i++) {
        pages.push(i);
      }
    } else {
      const halfVisible = Math.floor(maxVisiblePages / 2);
      let startPage = Math.max(1, this.currentPage - halfVisible);
      let endPage = Math.min(this.totalPages, startPage + maxVisiblePages - 1);
      
      if (endPage - startPage < maxVisiblePages - 1) {
        startPage = Math.max(1, endPage - maxVisiblePages + 1);
      }
      
      for (let i = startPage; i <= endPage; i++) {
        pages.push(i);
      }
    }
    
    return pages;
  }

  toggleFavorite(event: Event, card: Card): void {
    event.preventDefault();
    event.stopPropagation();
    this.favoritesService.toggleFavorite(card);
  }

  isFavorite(cardId: string): boolean {
    return this.favoritesService.isFavorite(cardId);
  }
}

@defer (when cards.length > 0 || allCards.length > 0) {
  <div class="container-fluid border border-2 rounded mt-3 mb-3 card-list-container">
    <div class="d-flex justify-content-between align-items-center flex-wrap p-3">
      <div>
        <h2 class="display-5 mb-0 fw-bold">Listado de cartas</h2>
        <div class="text-light">Cantidad de cartas: {{ cards.length }}</div>
      </div>
      <button class="btn btn-primary" routerLink="/card/add">Agregar carta</button>
    </div>

    <!-- Filtros -->
    <div class="filters-section p-3 border-top border-bottom border-secondary">
      <div class="row g-3 align-items-end">
        <div class="col-md-3">
          <label class="form-label text-light">Edición</label>
          <select class="form-select" [(ngModel)]="selectedCollection" (change)="applyFilters()">
            <option value="">Todas las ediciones</option>
            @for (collection of collections; track collection) {
              <option [value]="collection">{{ collection }}</option>
            }
          </select>
        </div>
        <div class="col-md-2">
          <label class="form-label text-light">Calidad</label>
          <select class="form-select" [(ngModel)]="selectedCondition" (change)="applyFilters()">
            <option value="">Todas las calidades</option>
            @for (condition of conditions; track condition) {
              <option [value]="condition">{{ condition }}</option>
            }
          </select>
        </div>
        <div class="col-md-2">
          <label class="form-label text-light">Precio mínimo</label>
          <input type="number" class="form-control" [(ngModel)]="minPrice" (input)="applyFilters()" placeholder="0€" min="0">
        </div>
        <div class="col-md-2">
          <label class="form-label text-light">Precio máximo</label>
          <input type="number" class="form-control" [(ngModel)]="maxPrice" (input)="applyFilters()" placeholder="∞" min="0">
        </div>
        <div class="col-md-3">
          <div class="d-flex gap-2">
            <button class="btn btn-secondary flex-grow-1" (click)="togglePriceSort()">
              @if (priceSort === 'none') {
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down-up" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M11.5 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L11 2.707V14.5a.5.5 0 0 0 .5.5m-7-14a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L4 13.293V1.5a.5.5 0 0 1 .5-.5"/>
                </svg>
                Ordenar por precio
              } @else if (priceSort === 'asc') {
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-sort-numeric-down" viewBox="0 0 16 16">
                  <path d="M12.438 1.668V7H11.39V2.684h-.051l-1.211.859v-.969l1.262-.906h1.046z"/>
                  <path fill-rule="evenodd" d="M11.36 14.098c-1.137 0-1.708-.657-1.762-1.278h1.004c.058.223.343.45.773.45.824 0 1.164-.829 1.133-1.856h-.059c-.148.39-.57.742-1.261.742-.91 0-1.72-.613-1.72-1.758 0-1.148.848-1.835 1.973-1.835 1.09 0 2.063.636 2.063 2.687 0 1.867-.723 2.848-2.145 2.848zm.062-2.735c.504 0 .933-.336.933-.972 0-.633-.398-1.008-.94-1.008-.52 0-.927.375-.927 1 0 .64.418.98.934.98"/>
                  <path d="M4.5 2.5a.5.5 0 0 0-1 0v9.793l-1.146-1.147a.5.5 0 0 0-.708.708l2 1.999.007.007a.497.497 0 0 0 .7-.006l2-2a.5.5 0 0 0-.707-.708L4.5 12.293z"/>
                </svg>
                Menor a mayor
              } @else {
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-sort-numeric-down-alt" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M11.36 7.098c-1.137 0-1.708-.657-1.762-1.278h1.004c.058.223.343.45.773.45.824 0 1.164-.829 1.133-1.856h-.059c-.148.39-.57.742-1.261.742-.91 0-1.72-.613-1.72-1.758 0-1.148.848-1.836 1.973-1.836 1.09 0 2.063.637 2.063 2.688 0 1.867-.723 2.848-2.145 2.848zm.062-2.735c.504 0 .933-.336.933-.972 0-.633-.398-1.008-.94-1.008-.52 0-.927.375-.927 1 0 .64.418.98.934.98"/>
                  <path d="M12.438 8.668V14H11.39V9.684h-.051l-1.211.859v-.969l1.262-.906h1.046zM4.5 13.5a.5.5 0 0 1-1 0V3.707L2.354 4.854a.5.5 0 1 1-.708-.708l2-1.999.007-.007a.5.5 0 0 1 .7.006l2 2a.5.5 0 1 1-.707.708L4.5 3.707z"/>
                </svg>
                Mayor a menor
              }
            </button>
            <button class="btn btn-outline-light" (click)="clearFilters()">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"/>
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="row g-4 p-4">
      @for (card of paginatedCards; track card._id) {
        <div class="col-6 col-sm-4 col-md-3 col-lg-2">
          <div class="card-wrapper" [class.is-favorite]="isFavorite(card._id)">
            <a class="card-image-link" routerLink="/card/detail/{{card._id}}" [attr.aria-label]="'Ver detalles de ' + card.name">
              <img class="card-image" [src]="card.imageUrl" [alt]="card.name" (dblclick)="toggleFavorite($event, card)">
            </a>
            <div class="card-info-wrapper">
              <div class="card-name-row">
                <div class="card-name">{{ card.name }}</div>
                <button class="favorite-btn-inline" 
                        (click)="toggleFavorite($event, card)" 
                        [class.is-favorite]="isFavorite(card._id)"
                        [attr.aria-label]="isFavorite(card._id) ? 'Quitar de favoritos' : 'Añadir a favoritos'">
                  @if (isFavorite(card._id)) {
                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
                    </svg>
                  } @else {
                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                      <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                    </svg>
                  }
                </button>
              </div>
              <div class="card-price">{{ card.price | currency:'EUR' }}</div>
            </div>
          </div>
        </div>
      }
    </div>

    <!-- Paginación -->
    @if (totalPages > 1) {
      <div class="pagination-section p-3 border-top border-secondary">
        <div class="d-flex justify-content-between align-items-center flex-wrap gap-3">
          <div class="text-light">
            Mostrando {{ (currentPage - 1) * itemsPerPage + 1 }} - {{ Math.min(currentPage * itemsPerPage, cards.length) }} de {{ cards.length }} cartas
          </div>
          
          <nav aria-label="Paginación de cartas">
            <ul class="pagination pagination-custom mb-0">
              <li class="page-item" [class.disabled]="currentPage === 1">
                <button class="page-link" (click)="previousPage()" [disabled]="currentPage === 1">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
                  </svg>
                </button>
              </li>
              
              @for (page of getPageNumbers(); track page) {
                <li class="page-item" [class.active]="currentPage === page">
                  <button class="page-link" (click)="goToPage(page)">{{ page }}</button>
                </li>
              }
              
              <li class="page-item" [class.disabled]="currentPage === totalPages">
                <button class="page-link" (click)="nextPage()" [disabled]="currentPage === totalPages">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"/>
                  </svg>
                </button>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    }
  </div>

} @placeholder () {
  <div class="container-fluid text-center">
    <h6 class="display-5 text-primary">Cargando Cards...</h6>
  </div>
}

// frontend react/src/components/card/CardList/CardList.tsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Card } from '../../../common/interfaces';
import { cardService } from '../../../services/cardService';
import { favoritesService } from '../../../services/favoritesService';
import './CardList.css';

export const CardList: React.FC = () => {
  const [allCards, setAllCards] = useState<Card[]>([]);
  const [cards, setCards] = useState<Card[]>([]);
  const [paginatedCards, setPaginatedCards] = useState<Card[]>([]);
  const [collections, setCollections] = useState<string[]>([]);
  const [conditions, setConditions] = useState<string[]>([]);
  const [favorites, setFavorites] = useState<string[]>([]);
  
  // Filtros
  const [selectedCollection, setSelectedCollection] = useState('');
  const [selectedCondition, setSelectedCondition] = useState('');
  const [minPrice, setMinPrice] = useState<number | null>(null);
  const [maxPrice, setMaxPrice] = useState<number | null>(null);
  
  // Ordenamiento
  const [priceSort, setPriceSort] = useState<'none' | 'asc' | 'desc'>('none');
  
  // Paginación
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 12;
  const totalPages = Math.ceil(cards.length / itemsPerPage);
  
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadCards();
    const unsubscribe = favoritesService.subscribe(() => {
      setFavorites(favoritesService.getFavorites().map(f => f._id));
    });
    return unsubscribe;
  }, []);

  const loadCards = async () => {
    try {
      const data = await cardService.getCards();
      setAllCards(data.status);
      setCards(data.status);
      extractFilters(data.status);
      setLoading(false);
    } catch (error) {
      console.error('Error carga de cards:', error);
      setLoading(false);
    }
  };

  const extractFilters = (cardsData: Card[]) => {
    const uniqueCollections = [...new Set(cardsData.map(card => card.collection))].sort();
    const uniqueConditions = [...new Set(cardsData.map(card => card.condition))].sort();
    setCollections(uniqueCollections);
    setConditions(uniqueConditions);
  };

  const applyFilters = () => {
    let filtered = [...allCards];
    
    if (selectedCollection) {
      filtered = filtered.filter(card => card.collection === selectedCollection);
    }
    
    if (selectedCondition) {
      filtered = filtered.filter(card => card.condition === selectedCondition);
    }
    
    if (minPrice !== null && minPrice > 0) {
      filtered = filtered.filter(card => card.price >= minPrice);
    }
    
    if (maxPrice !== null && maxPrice > 0) {
      filtered = filtered.filter(card => card.price <= maxPrice);
    }
    
    if (priceSort === 'asc') {
      filtered.sort((a, b) => a.price - b.price);
    } else if (priceSort === 'desc') {
      filtered.sort((a, b) => b.price - a.price);
    }
    
    setCards(filtered);
    setCurrentPage(1);
    updatePagination(filtered);
  };

  const updatePagination = (cardsData: Card[]) => {
    const startIndex = (currentPage - 1) * itemsPerPage;
    const endIndex = startIndex + itemsPerPage;
    setPaginatedCards(cardsData.slice(startIndex, endIndex));
  };

  useEffect(() => {
    updatePagination(cards);
  }, [currentPage, cards]);

  const clearFilters = () => {
    setSelectedCollection('');
    setSelectedCondition('');
    setMinPrice(null);
    setMaxPrice(null);
    setPriceSort('none');
    setCards(allCards);
    setCurrentPage(1);
    setPaginatedCards(allCards.slice(0, itemsPerPage));
  };

  const togglePriceSort = () => {
    const newSort = priceSort === 'none' ? 'asc' : priceSort === 'asc' ? 'desc' : 'none';
    setPriceSort(newSort);
  };

  const goToPage = (page: number) => {
    if (page >= 1 && page <= totalPages) {
      setCurrentPage(page);
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  const getPageNumbers = (): number[] => {
    const pages: number[] = [];
    const maxVisiblePages = 5;
    
    if (totalPages <= maxVisiblePages) {
      for (let i = 1; i <= totalPages; i++) {
        pages.push(i);
      }
    } else {
      const halfVisible = Math.floor(maxVisiblePages / 2);
      let startPage = Math.max(1, currentPage - halfVisible);
      let endPage = Math.min(totalPages, startPage + maxVisiblePages - 1);
      
      if (endPage - startPage < maxVisiblePages - 1) {
        startPage = Math.max(1, endPage - maxVisiblePages + 1);
      }
      
      for (let i = startPage; i <= endPage; i++) {
        pages.push(i);
      }
    }
    
    return pages;
  };

  const toggleFavorite = (e: React.MouseEvent, card: Card) => {
    e.preventDefault();
    e.stopPropagation();
    favoritesService.toggleFavorite(card);
    setFavorites(favoritesService.getFavorites().map(f => f._id));
  };

  const isFavorite = (cardId: string) => {
    return favorites.includes(cardId);
  };

  if (loading) {
    return <div className="container-fluid p-4">Cargando cartas...</div>;
  }

  return (
    <div className="container-fluid border border-2 rounded mt-3 mb-3 card-list-container">
      <div className="d-flex justify-content-between align-items-center flex-wrap p-3">
        <div>
          <h2 className="display-5 mb-0 fw-bold">Listado de cartas</h2>
          <div className="text-light">Cantidad de cartas: {cards.length}</div>
        </div>
        <Link to="/card/add" className="btn btn-primary">Agregar carta</Link>
      </div>

      {/* Filtros */}
      <div className="filters-section p-3 border-top border-bottom border-secondary">
        <div className="row g-3 align-items-end">
          <div className="col-md-3">
            <label className="form-label text-light">Edición</label>
            <select 
              className="form-select" 
              value={selectedCollection}
              onChange={(e) => {
                setSelectedCollection(e.target.value);
                applyFilters();
              }}
            >
              <option value="">Todas las ediciones</option>
              {collections.map(collection => (
                <option key={collection} value={collection}>{collection}</option>
              ))}
            </select>
          </div>
          <div className="col-md-2">
            <label className="form-label text-light">Calidad</label>
            <select 
              className="form-select" 
              value={selectedCondition}
              onChange={(e) => {
                setSelectedCondition(e.target.value);
                applyFilters();
              }}
            >
              <option value="">Todas las calidades</option>
              {conditions.map(condition => (
                <option key={condition} value={condition}>{condition}</option>
              ))}
            </select>
          </div>
          <div className="col-md-2">
            <label className="form-label text-light">Precio mínimo</label>
            <input 
              type="number" 
              className="form-control" 
              placeholder="0€" 
              min="0"
              value={minPrice ?? ''}
              onChange={(e) => {
                setMinPrice(e.target.value ? Number(e.target.value) : null);
                applyFilters();
              }}
            />
          </div>
          <div className="col-md-2">
            <label className="form-label text-light">Precio máximo</label>
            <input 
              type="number" 
              className="form-control" 
              placeholder="∞" 
              min="0"
              value={maxPrice ?? ''}
              onChange={(e) => {
                setMaxPrice(e.target.value ? Number(e.target.value) : null);
                applyFilters();
              }}
            />
          </div>
          <div className="col-md-3">
            <div className="d-flex gap-2">
              <button className="btn btn-secondary flex-grow-1" onClick={togglePriceSort}>
                {priceSort === 'none' && '📊 Ordenar por precio'}
                {priceSort === 'asc' && '⬆️ Menor a mayor'}
                {priceSort === 'desc' && '⬇️ Mayor a menor'}
              </button>
              <button className="btn btn-secondary" onClick={clearFilters}>Limpiar</button>
            </div>
          </div>
        </div>
      </div>

      {/* Listado de cartas */}
      <div className="cards-grid p-3">
        {paginatedCards.map(card => (
          <div key={card._id}>
            <Link to={`/card/detail/${card._id}`} className="card-link">
              <div className="card card-item">
                <img src={card.imageUrl} className="card-img-top" alt={card.name} />
                <div className="card-body">
                  <h5 className="card-title">{card.name}</h5>
                  <p className="card-text text-light">
                    <small>{card.collection} • {card.condition}</small>
                  </p>
                  <div className="d-flex justify-content-between align-items-center">
                    <span className="h5 mb-0">{card.price.toFixed(2)}€</span>
                    <button 
                      className={`btn btn-sm ${isFavorite(card._id) ? 'btn-danger' : 'btn-outline-danger'}`}
                      onClick={(e) => toggleFavorite(e, card)}
                    >
                      ❤️
                    </button>
                  </div>
                </div>
              </div>
            </Link>
          </div>
        ))}
      </div>

      {/* Paginación */}
      {totalPages > 1 && (
        <div className="pagination-section p-3 border-top d-flex justify-content-center gap-2 flex-wrap">
          <button 
            className="btn btn-secondary"
            onClick={() => goToPage(currentPage - 1)}
            disabled={currentPage === 1}
          >
            ← Anterior
          </button>
          
          {getPageNumbers().map(page => (
            <button
              key={page}
              className={`btn ${page === currentPage ? 'btn-primary' : 'btn-outline-primary'}`}
              onClick={() => goToPage(page)}
            >
              {page}
            </button>
          ))}
          
          <button 
            className="btn btn-secondary"
            onClick={() => goToPage(currentPage + 1)}
            disabled={currentPage === totalPages}
          >
            Siguiente →
          </button>
        </div>
      )}
    </div>
  );
};
